name: CI-CD-Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run python
        run: python hello.py
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: full-repo
          path: .
